name: Node.js - Bump version on release

on:
  release:
    types:
      - published

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: version
        uses: vemel/nextversion@main
        with:
          version-path: ./package.json
          type: semver
          result: ${{ github.event.payload.tag_name }}
          update-path: |
            ./package.json
            ./src/constants.js
            ./README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version to ${{ steps.version.outputs.result }}"
