name: Node.js - Bump version on demand

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Release bump: major, minor or micro"
        required: true
        default: "micro"
      release:
        description: "Release type: stable, rc, alpha, or beta"
        required: true
        default: "stable"

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: version
        uses: vemel/nextversion@main
        with:
          path: ./package.json
          type: semver
          result: ${{ github.event.inputs.bump }}
          release: ${{ github.event.inputs.release }}
          update: |
            ./package.json
            ./src/constants.js
            ./README.md
      - name: Update CHANGELOG.md
        id: version
        uses: vemel/nextchange@main
        with:
          release: ${{ steps.version.outputs.result }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version to ${{ steps.version.outputs.result }}"
