name: Python - Bump version on release

on:
  release: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: version
        uses: actions/next-version@v1
        with:
          version-path: ./setup.cfg
          type: pep440
          result: ${{ github.event.release.tag_name }}
          update-path: |
            ./setup.cfg
            ./pyproject.toml
            ./mypackage/version.txt
            ./README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version to ${{ steps.version.outputs.result }}"
