name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version. Leave auto to get version from unreleased notes"
        required: true
        default: "auto"
      is-prerelease:
        description: "Create a Release Candidate for auto version: true or false"
        required: true
        default: "false"

jobs:
  release-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get notes from CHANGELOG.md
        id: changelog
        uses: vemel/nextrelease@main
        with:
          sanitize: "true"
      - name: Get new auto version
        id: auto-version
        uses: vemel/nextversion@main
        with:
          version-path: ./package.json
          result: ${{ steps.changelog.outputs.label }}
          type: semver
          prerelease: ${{ github.event.inputs.is-prerelease }}
          prerelease-type: rc
      - name: Get new version
        id: version
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const inputVersion = ${{ github.event.inputs.is-prerelease }};
            if (inputVersion && inputVersion !== "auto") return inputVersion;
            return ${{ toJSON(steps.auto-version.outputs.result) }};
      - name: Update version
        uses: vemel/nextversion@main
        with:
          version-path: ./package.json
          type: semver
          result: ${{ steps.version.outputs.result }}
          update-path: |
            ./package.json
            ./README.md
      - name: Update changelog
        uses: vemel/nextrelease@main
        with:
          sanitize: "true"
          release: ${{ steps.version.outputs.result }}
      - name: Commit changes
        run: |
          VERSION=${{ toJSON(steps.version.outputs.result) }}
          BRANCH="release/${{ steps.version.outputs.result }}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b ${BRANCH}
          git commit -am "Bump version to $VERSION"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.version.outputs.result }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Bump version to ${{ steps.version.outputs.result }}"
          body: ${{ toJSON(steps.changelog.outputs.result) }}
